// Project Amanda -- protocol v1 conformance tests.
//
// These mirror avatar-orchestrator/tests/test_protocol.py. If a case here needs
// changing, that is probably a protocol version bump rather than a fix.
//
// Run them from the editor: Tools -> Session Frontend -> Automation, filter for
// "Amanda". Or from a command line:
//
//     UnrealEditor-Cmd.exe <Project>.uproject -ExecCmds="Automation RunTests Amanda; Quit" -unattended -nopause -testexit="Automation Test Queue Empty"

#include "AmandaBridgeProtocol.h"
#include "AmandaBridgeTypes.h"
#include "Misc/AutomationTest.h"
#include "Runtime/Launch/Resources/Version.h"

#if WITH_DEV_AUTOMATION_TESTS

#include "Tests/AmandaSampleSession.inl"

// EAutomationTestFlags became an enum class in UE 5.5 and the mask constants
// moved out of the enum's scope. This keeps the tests building either side of
// that change.
#if ENGINE_MAJOR_VERSION > 5 || (ENGINE_MAJOR_VERSION == 5 && ENGINE_MINOR_VERSION >= 5)
	#define AMANDA_TEST_FLAGS (EAutomationTestFlags_ApplicationContextMask | EAutomationTestFlags::ProductFilter)
#else
	#define AMANDA_TEST_FLAGS (EAutomationTestFlags::ApplicationContextMask | EAutomationTestFlags::ProductFilter)
#endif

// --------------------------------------------------------------------------
// The real wire format
// --------------------------------------------------------------------------

IMPLEMENT_SIMPLE_AUTOMATION_TEST(
	FAmandaSampleSessionTest, "Amanda.Protocol.SampleSession", AMANDA_TEST_FLAGS)

bool FAmandaSampleSessionTest::RunTest(const FString& Parameters)
{
	// The fixture is generated by the Python reference implementation, so this
	// is the exact byte stream the orchestrator sends -- and it exercises every
	// event in the protocol.
	TSet<FString> Seen;

	for (const TCHAR* Line : AmandaSampleSession)
	{
		FAmandaEnvelope Envelope;
		FString Error;
		if (!TestTrue(FString::Printf(TEXT("decodes: %s"), Line),
			FAmandaProtocol::Decode(FString(Line), Envelope, Error)))
		{
			AddError(FString::Printf(TEXT("  reason: %s"), *Error));
			continue;
		}

		TestTrue(FString::Printf(TEXT("'%s' is a known event"), *Envelope.Event),
			FAmandaProtocol::IsKnownEvent(Envelope.Event));
		Seen.Add(Envelope.Event);

		// Every payload the orchestrator produces must parse without error.
		if (Envelope.Event == AmandaEvents::PerformanceUpdate)
		{
			FAmandaPerformanceUpdate Update;
			TestTrue(TEXT("performance payload parses"),
				FAmandaProtocol::ParsePerformance(Envelope, Update, Error));
			TestNotEqual(TEXT("preset resolved"), Update.Preset, EAmandaPreset::Unknown);
		}
		else if (Envelope.Event == AmandaEvents::GazeSetTarget)
		{
			FAmandaGaze Gaze;
			TestTrue(TEXT("gaze payload parses"), FAmandaProtocol::ParseGaze(Envelope, Gaze, Error));
			TestNotEqual(TEXT("target resolved"), Gaze.Target, EAmandaGazeTarget::Unknown);
		}
		else if (Envelope.Event == AmandaEvents::GestureTrigger)
		{
			FAmandaGesture Gesture;
			TestTrue(TEXT("gesture payload parses"),
				FAmandaProtocol::ParseGesture(Envelope, Gesture, Error));
		}
		else if (Envelope.Event == AmandaEvents::UserDetected)
		{
			bool bPresent = false;
			TestTrue(TEXT("presence payload parses"),
				FAmandaProtocol::ParseUserPresence(Envelope, bPresent, Error));
		}
	}

	TestEqual(TEXT("the sample session exercises all fifteen events"), Seen.Num(), 15);
	return true;
}

// --------------------------------------------------------------------------
// Envelope validation
// --------------------------------------------------------------------------

IMPLEMENT_SIMPLE_AUTOMATION_TEST(
	FAmandaEnvelopeTest, "Amanda.Protocol.Envelope", AMANDA_TEST_FLAGS)

bool FAmandaEnvelopeTest::RunTest(const FString& Parameters)
{
	FAmandaEnvelope Envelope;
	FString Error;

	TestFalse(TEXT("rejects non-JSON"),
		FAmandaProtocol::Decode(TEXT("not json at all"), Envelope, Error));

	TestFalse(TEXT("rejects protocol version 2"),
		FAmandaProtocol::Decode(
			TEXT("{\"version\":2,\"event\":\"avatar.reset\",\"payload\":{}}"), Envelope, Error));

	TestFalse(TEXT("rejects a missing version"),
		FAmandaProtocol::Decode(TEXT("{\"event\":\"avatar.reset\"}"), Envelope, Error));

	TestFalse(TEXT("rejects a missing event"),
		FAmandaProtocol::Decode(TEXT("{\"version\":1,\"payload\":{}}"), Envelope, Error));

	// Payload and timestamp are optional on the wire.
	TestTrue(TEXT("accepts a bare envelope"),
		FAmandaProtocol::Decode(TEXT("{\"version\":1,\"event\":\"avatar.reset\"}"), Envelope, Error));
	TestTrue(TEXT("an absent payload becomes an empty object"), Envelope.Payload.IsValid());
	TestEqual(TEXT("timestamp defaults to zero"), Envelope.Timestamp, 0.0);

	return true;
}

// --------------------------------------------------------------------------
// Forward compatibility -- the rules that let the two sides ship separately
// --------------------------------------------------------------------------

IMPLEMENT_SIMPLE_AUTOMATION_TEST(
	FAmandaCompatibilityTest, "Amanda.Protocol.Compatibility", AMANDA_TEST_FLAGS)

bool FAmandaCompatibilityTest::RunTest(const FString& Parameters)
{
	FAmandaEnvelope Envelope;
	FString Error;

	// Rule 2: an unrecognised event decodes, so the receiver can skip it rather
	// than dropping the connection.
	TestTrue(TEXT("an unknown event still decodes"),
		FAmandaProtocol::Decode(
			TEXT("{\"version\":1,\"event\":\"breath.hold\",\"payload\":{}}"), Envelope, Error));
	TestFalse(TEXT("and is reported as unknown"), FAmandaProtocol::IsKnownEvent(Envelope.Event));

	// Rule 1: unrecognised payload fields are ignored, so the orchestrator can
	// add optional fields without a version bump.
	TestTrue(TEXT("decodes a payload carrying a field we do not know"),
		FAmandaProtocol::Decode(
			TEXT("{\"version\":1,\"event\":\"performance.update\",")
			TEXT("\"payload\":{\"preset\":\"warm\",\"intensity\":0.3,\"jaw_tension\":0.4}}"),
			Envelope, Error));

	FAmandaPerformanceUpdate Update;
	TestTrue(TEXT("and parses it"), FAmandaProtocol::ParsePerformance(Envelope, Update, Error));
	TestEqual(TEXT("preset survives"), Update.Preset, EAmandaPreset::Warm);
	TestFalse(TEXT("the unknown field does not become an override"), Update.bHasSmile);

	// An unauthored preset degrades to a calm face, not a frozen one.
	TestTrue(TEXT("decodes an unknown preset"),
		FAmandaProtocol::Decode(
			TEXT("{\"version\":1,\"event\":\"performance.update\",")
			TEXT("\"payload\":{\"preset\":\"smug\",\"intensity\":0.2}}"),
			Envelope, Error));
	TestTrue(TEXT("and parses it"), FAmandaProtocol::ParsePerformance(Envelope, Update, Error));
	TestEqual(TEXT("falls back to neutral attentive"),
		FAmandaProtocol::Animatable(Update.Preset), EAmandaPreset::NeutralAttentive);

	return true;
}

// --------------------------------------------------------------------------
// Payload validation
// --------------------------------------------------------------------------

IMPLEMENT_SIMPLE_AUTOMATION_TEST(
	FAmandaPayloadTest, "Amanda.Protocol.Payloads", AMANDA_TEST_FLAGS)

bool FAmandaPayloadTest::RunTest(const FString& Parameters)
{
	FAmandaEnvelope Envelope;
	FString Error;

	// A missing required field is a real bug and stays an error, unlike the
	// compatibility cases above.
	FAmandaProtocol::Decode(
		TEXT("{\"version\":1,\"event\":\"performance.update\",\"payload\":{\"intensity\":0.2}}"),
		Envelope, Error);
	FAmandaPerformanceUpdate Update;
	TestFalse(TEXT("a performance update without a preset is refused"),
		FAmandaProtocol::ParsePerformance(Envelope, Update, Error));

	FAmandaProtocol::Decode(
		TEXT("{\"version\":1,\"event\":\"performance.update\",\"payload\":{\"preset\":\"warm\"}}"),
		Envelope, Error);
	TestFalse(TEXT("a performance update without an intensity is refused"),
		FAmandaProtocol::ParsePerformance(Envelope, Update, Error));

	// Optional overrides stay absent rather than defaulting to something that
	// looks like a real value.
	FAmandaProtocol::Decode(
		TEXT("{\"version\":1,\"event\":\"performance.update\",")
		TEXT("\"payload\":{\"preset\":\"considering\",\"intensity\":0.28,\"eye_contact\":0.55}}"),
		Envelope, Error);
	TestTrue(TEXT("parses"), FAmandaProtocol::ParsePerformance(Envelope, Update, Error));
	TestTrue(TEXT("the supplied override is flagged"), Update.bHasEyeContact);
	TestEqual(TEXT("and carried"), Update.EyeContact, 0.55f, 0.001f);
	TestFalse(TEXT("an omitted override is not flagged"), Update.bHasSmile);
	TestEqual(TEXT("transition falls back to the default"), Update.TransitionMs, 450);

	// Clamped rather than refused: by the time a bad coefficient reaches the
	// renderer, refusing it only means the avatar misses a direction.
	FAmandaProtocol::Decode(
		TEXT("{\"version\":1,\"event\":\"performance.update\",")
		TEXT("\"payload\":{\"preset\":\"warm\",\"intensity\":1.4}}"),
		Envelope, Error);
	TestTrue(TEXT("an out-of-range intensity still parses"),
		FAmandaProtocol::ParsePerformance(Envelope, Update, Error));
	TestEqual(TEXT("clamped to 1.0"), Update.Intensity, 1.0f, 0.001f);

	// Speech: the cancel defaults matter, because barge-in uses them.
	FAmandaProtocol::Decode(
		TEXT("{\"version\":1,\"event\":\"speech.cancelled\",\"payload\":{\"utterance_id\":\"u_1\"}}"),
		Envelope, Error);
	FAmandaSpeech Speech;
	TestTrue(TEXT("a bare cancellation parses"),
		FAmandaProtocol::ParseSpeech(Envelope, EAmandaSpeechPhase::Cancelled, Speech, Error));
	TestEqual(TEXT("reason defaults to barge-in"), Speech.CancelReason, EAmandaCancelReason::BargeIn);
	TestEqual(TEXT("fade defaults to 80ms"), Speech.FadeMs, 80);

	FAmandaProtocol::Decode(
		TEXT("{\"version\":1,\"event\":\"speech.started\",\"payload\":{\"utterance_id\":\"u_1\"}}"),
		Envelope, Error);
	Speech = FAmandaSpeech();
	TestTrue(TEXT("a bare speech start parses"),
		FAmandaProtocol::ParseSpeech(Envelope, EAmandaSpeechPhase::Started, Speech, Error));
	TestEqual(TEXT("audio channel defaults"), Speech.AudioChannel, FString(TEXT("stream")));
	TestEqual(TEXT("sample rate defaults"), Speech.SampleRate, 24000);

	// Gaze hold of zero means "until told otherwise", not "immediately".
	FAmandaProtocol::Decode(
		TEXT("{\"version\":1,\"event\":\"gaze.set_target\",\"payload\":{\"target\":\"distant\"}}"),
		Envelope, Error);
	FAmandaGaze Gaze;
	TestTrue(TEXT("a bare gaze target parses"), FAmandaProtocol::ParseGaze(Envelope, Gaze, Error));
	TestEqual(TEXT("target"), Gaze.Target, EAmandaGazeTarget::Distant);
	TestEqual(TEXT("hold defaults to zero"), Gaze.HoldMs, 0);
	TestEqual(TEXT("transition defaults to 220ms"), Gaze.TransitionMs, 220);

	return true;
}

#endif // WITH_DEV_AUTOMATION_TESTS
